[[headers]]
  for = "/*.json"
  [headers.values]
    mimeType = "application/manifest+json"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*"
    [headers.values]
        X-Frame-Options = "sameorigin"
