[[headers]]
  for = "/*.json"
  [headers.values]
    mimeType = "application/manifest+json"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*"
    [headers.values]
        X-Frame-Options = "sameorigin"

[[redirects]]
  from = "https://itadakimasu.netlify.app/*"
  to = "https://itadakimasu.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://itadakimasu.thayn.me/*"
  to = "https://itadakimasu.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://itadakimasu.thayn.me/*"
  to = "https://itadakimasu.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.itadakimasu.app/*"
  to = "https://itadakimasu.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://install.itadakimasu.app/"
  to = "https://github.com/AnalogCyan/itadakimasu#readme"
  status = 301
  force = true

[[redirects]]
  from = "https://install.itadakimasu.app/windows/"
  to = "ms-windows-store://pdp/?ProductId=9p3ljk22jpch&mode=mini"
  status = 301
  force = true
